name: Build Flutter Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean build files and locks
        run: |
          rm -f pubspec.lock
          flutter clean

      - name: Create native Android structure
        run: flutter create . --platforms android --android-language kotlin

      # PASO DEFINITIVO: Configura Kotlin en el pluginManagement de Gradle para resolver :jni
      - name: Configure Kotlin Plugin for Gradle KTS
        run: |
          echo -e 'pluginManagement {\n    plugins {\n        id("org.jetbrains.kotlin.android") version "1.8.22" apply false\n    }\n}\n' | cat - android/settings.gradle.kts > temp && mv temp android/settings.gradle.kts || true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
